# Numpy Concepts

In [1]:
import numpy


In [2]:
chars = numpy.array(['r','a','j','a','t'])
numbs = numpy.array([2,8,4,2,3,5])
print(chars, numbs)

['r' 'a' 'j' 'a' 't'] [2 8 4 2 3 5]


# Six ways to create Arrays

In [3]:
first_way= numpy.array([2,8,4,2,6,4], float)
print(first_way)

[2. 8. 4. 2. 6. 4.]


In [4]:
second_way= numpy.linspace(0,50)
print(second_way)

[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]


In [5]:
third_way = numpy.logspace(0,50)
print(third_way)

[1.00000000e+00 1.04811313e+01 1.09854114e+02 1.15139540e+03
 1.20679264e+04 1.26485522e+05 1.32571137e+06 1.38949549e+07
 1.45634848e+08 1.52641797e+09 1.59985872e+10 1.67683294e+11
 1.75751062e+12 1.84206997e+13 1.93069773e+14 2.02358965e+15
 2.12095089e+16 2.22299648e+17 2.32995181e+18 2.44205309e+19
 2.55954792e+20 2.68269580e+21 2.81176870e+22 2.94705170e+23
 3.08884360e+24 3.23745754e+25 3.39322177e+26 3.55648031e+27
 3.72759372e+28 3.90693994e+29 4.09491506e+30 4.29193426e+31
 4.49843267e+32 4.71486636e+33 4.94171336e+34 5.17947468e+35
 5.42867544e+36 5.68986603e+37 5.96362332e+38 6.25055193e+39
 6.55128557e+40 6.86648845e+41 7.19685673e+42 7.54312006e+43
 7.90604321e+44 8.28642773e+45 8.68511374e+46 9.10298178e+47
 9.54095476e+48 1.00000000e+50]


In [6]:
fourth_way = numpy.arange(0,50)
print(fourth_way)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [7]:
fifth_way = numpy.zeros(10)
print(fifth_way)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
sixth_way = numpy.ones(10)
print(sixth_way)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Working with Matrices

In [9]:
arr= numpy.array([
            [1,2,3],
            [4,5,6]
            ])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr.dtype)       
print(arr.ndim)
print(arr.shape)     
print(arr.size)         
print(arr.flatten())

int32
2
(2, 3)
6
[1 2 3 4 5 6]


In [11]:
# Array Conversion:
arr2 = numpy.array([
            [1,2,3,6,2,9],
            [4,5,6,7,5,3]
            ])

In [12]:
# convert 1D array -> Multi_D array (3R,4C)
print(arr2.reshape(3,4))

[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]


In [13]:
# convert 1D array -> Multi_D array "2 arrays of(2Rows ,3Columns)"
arr3=arr2.reshape(2,2,3)  

print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [14]:
m1= numpy.matrix('1,2,3,4;5,6,7,8')   #2Rows , 4Columns
print(m1)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
m2= numpy.matrix('1,2;3,4;5,6;7,8')   #4Rows ,2Columns
print(m2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
m3= numpy.matrix('1,2,3;4 5,6 ;1 6 7')   #3Rows ,3Columns
print(m3)

[[1 2 3]
 [4 5 6]
 [1 6 7]]


In [17]:
print(numpy.diagonal(m3))
print(m3.min())
print(m3.max())

[1 5 7]
1
7


# Matrix: Addition & Multiplication

In [18]:
a1=numpy.matrix('1,2 3;6 4,5;1,6 7')
a2=numpy.matrix('1,2 3;6 8,5;2,6 7')

In [19]:
#Addition of 2 Matrix

add=a1+a2
print(add)

[[ 2  4  6]
 [12 12 10]
 [ 3 12 14]]


In [20]:
#Multiplication of 2 Matrix

mul=a1*a2
print(mul)

[[19 36 34]
 [40 74 73]
 [51 92 82]]
